---
- name: Creating users by ansible
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  vars_files: 
    - vars/users.yaml

  tasks:
    - name: Adding users from hash file 
      user:
        name: "{{ user.login }}"
        password: "{{ user.password | password_hash('sha512') }}"
        comment: "{{ user.comment }}"
        state: present
      no_log: true
      loop: "{{ users_to_add }}"
      loop_control:
        loop_var: user
        pause: 5