- name: Installing DB
  become: true  
  block:
    - name: Install 'mariadb-server' and 'MySQL-python' packages
      yum:
          name: "{{ packages }}"
          state: present

    - name: Ensure 'mariadb' service is started and enabled
      service: 
        name: mariadb 
        state: started 
        enabled: true

    - name: Create database "{{ wp_db_name }}" database
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present

    - name: Create DB user with ALL permissions to "{{ wp_db_name }}"
      mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
      no_log: true
  tags: db
